import Head from "next/head";
import Profile from "@/components/Profile";
import Filter from "@/components/Filter";
import Footer from "@/components/Footer";
import { useContext } from "react";
import { ThemeContext } from "@/components/ThemeContext";

export default function Home() {
  const { darkMode } = useContext(ThemeContext);
  return (
    <div className={`app ${darkMode && "dark-theme"}`}>
      <Head>
        <title>Jeremy's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://images.secretlab.co/theme/common/favicon-32x32.png"
        />
      </Head>

      <main>
        <Profile />
        <Filter />
        <Footer />
      </main>
    </div>
  );
}
